export default {
  toggleFacilityFilter: "TOGGLE_FACILITY_FILTER",
  fetchUtilities: "FETCH_UTILITIES",
  fetchUtilityTypes: "FETCH_UTILITY_TYPES",
  fetchServices: "FETCH_SERVICES",
  fetchServiceTypes: "FETCH_SERVICE_TYPES",
  fetchResources: "FETCH_RESOURCES",
  fetchResourceTypes: "FETCH_RESOURCE_TYPES",
  fetchRegulatoryStatuses: "FETCH_REGULATORY_STATUSES",
  fetchOperationalStatuses: "FETCH_OPERATIONAL_STATUSES",
  fetchDistricts: "FETCH_DISTRICTS",
  fetchOwners: "FETCH_OWNERS",
  fetchFacilities: "FETCH_FACILITIES",
  fetchFacilityTypes: "FETCH_FACILITY_TYPES",
  fetchCurrentBasic: "FETCH_CURRENT_BASIC",
  fetchCurrentResources: "FETCH_CURRENT_RESOURCES",
  fetchCurrentServices: "FETCH_CURRENT_SERVICES",
  fetchCurrentUtilities: "FETCH_CURRENT_UTILITIES",
  setActivePage: "SET_ACTIVE_PAGE",
  setActiveFacilityPage: "SET_ACTIVE_FACILITY_PAGE",
  fetchUsers: "FETCH_USERS",
  userLogin: "USER_LOGIN",
  userLogout: "USER_LOGOUT",
  fetchUserDetails: "FETCH_USER_DETAILS",
  dependacyError: "DEPENDANCY_ERROR"
};
