// flow-typed signature: e1fcdb7564120a53d1a8867885797e2f
// flow-typed version: <<STUB>>/js-file-download_v^0.4.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-file-download'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-file-download' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-file-download/file-download' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-file-download/file-download.js' {
  declare module.exports: $Exports<'js-file-download/file-download'>;
}
