// flow-typed signature: 48f60d5973a403ae4eb495869aba1d0f
// flow-typed version: <<STUB>>/loopback-connector-mysql_v^5.2.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loopback-connector-mysql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loopback-connector-mysql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loopback-connector-mysql/example/app' {
  declare module.exports: any;
}

declare module 'loopback-connector-mysql/lib/discovery' {
  declare module.exports: any;
}

declare module 'loopback-connector-mysql/lib/enumFactory' {
  declare module.exports: any;
}

declare module 'loopback-connector-mysql/lib/migration' {
  declare module.exports: any;
}

declare module 'loopback-connector-mysql/lib/mysql' {
  declare module.exports: any;
}

declare module 'loopback-connector-mysql/lib/set-http-code' {
  declare module.exports: any;
}

declare module 'loopback-connector-mysql/lib/transaction' {
  declare module.exports: any;
}

declare module 'loopback-connector-mysql/pretest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loopback-connector-mysql/example/app.js' {
  declare module.exports: $Exports<'loopback-connector-mysql/example/app'>;
}
declare module 'loopback-connector-mysql/index' {
  declare module.exports: $Exports<'loopback-connector-mysql'>;
}
declare module 'loopback-connector-mysql/index.js' {
  declare module.exports: $Exports<'loopback-connector-mysql'>;
}
declare module 'loopback-connector-mysql/lib/discovery.js' {
  declare module.exports: $Exports<'loopback-connector-mysql/lib/discovery'>;
}
declare module 'loopback-connector-mysql/lib/enumFactory.js' {
  declare module.exports: $Exports<'loopback-connector-mysql/lib/enumFactory'>;
}
declare module 'loopback-connector-mysql/lib/migration.js' {
  declare module.exports: $Exports<'loopback-connector-mysql/lib/migration'>;
}
declare module 'loopback-connector-mysql/lib/mysql.js' {
  declare module.exports: $Exports<'loopback-connector-mysql/lib/mysql'>;
}
declare module 'loopback-connector-mysql/lib/set-http-code.js' {
  declare module.exports: $Exports<'loopback-connector-mysql/lib/set-http-code'>;
}
declare module 'loopback-connector-mysql/lib/transaction.js' {
  declare module.exports: $Exports<'loopback-connector-mysql/lib/transaction'>;
}
declare module 'loopback-connector-mysql/pretest.js' {
  declare module.exports: $Exports<'loopback-connector-mysql/pretest'>;
}
