// flow-typed signature: ef329e651870710d24b7f280acc95ebc
// flow-typed version: <<STUB>>/react-materialize_v^1.0.16/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-materialize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-materialize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-materialize/lib/Autocomplete' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Autocomplete/Autocomplete' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Autocomplete/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Badge' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Badge/Badge' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Badge/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Breadcrumb/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Breadcrumb/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Button' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Button/Button' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Button/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Card' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Card/Card' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Card/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/CardPanel' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/CardPanel/CardPanel' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/CardPanel/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/CardTitle' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/CardTitle/CardTitle' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/CardTitle/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Carousel' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Carousel/Carousel' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Carousel/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Chip' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Chip/Chip' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Chip/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Col' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Col/Col' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Col/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Collapsible' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Collapsible/Collapsible' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Collapsible/CollapsibleItem' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Collapsible/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/CollapsibleItem' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Collection' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Collection/Collection' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Collection/CollectionItem' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Collection/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/CollectionItem' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/constants' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Container' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Container/Container' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Container/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Divider' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Divider/Divider' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Divider/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Dropdown' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Dropdown/Dropdown' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Dropdown/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Footer' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Footer/Footer' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Footer/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Icon' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Icon/Icon' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Icon/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/idgen' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/index.old' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Input' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Input/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Input/Input' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/MediaBox' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/MediaBox/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/MediaBox/MediaBox' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/MenuItem' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/MenuItem/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/MenuItem/MenuItem' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Modal' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Modal/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Modal/Modal' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Navbar' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Navbar/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Navbar/Navbar' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/NavItem' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/NavItem/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/NavItem/NavItem' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Overlay' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/OverlayTrigger' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/OverlayTrigger/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/OverlayTrigger/Overlay' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/OverlayTrigger/OverlayTrigger' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Pagination' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Pagination/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Pagination/Pagination' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Pagination/PaginationButton' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/PaginationButton' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Parallax' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Parallax/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Parallax/Parallax' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Preloader' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Preloader/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Preloader/Preloader' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/ProgressBar/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/ProgressBar/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Row' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Row/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Row/Row' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/SearchForm' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/SearchForm/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/SearchForm/SearchForm' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Section' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Section/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Section/Section' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/SideNav' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/SideNav/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/SideNav/SideNav' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/SideNav/SideNavItem' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/SideNavItem' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Slide' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Slide/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Slide/Slide' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Slider' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Slider/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Slider/Slider' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Spinner' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Spinner/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Spinner/Spinner' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Tab' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Tab/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Tab/Tab' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Table' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Table/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Table/Table' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Tabs' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Tabs/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Tabs/Tabs' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Tag' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Tag/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Tag/Tag' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Toast' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Toast/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/Toast/Toast' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/UserView' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/UserView/index' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/UserView/UserView' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/utils/constants' {
  declare module.exports: any;
}

declare module 'react-materialize/lib/utils/idgen' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-materialize/lib/Autocomplete.js' {
  declare module.exports: $Exports<'react-materialize/lib/Autocomplete'>;
}
declare module 'react-materialize/lib/Autocomplete/Autocomplete.js' {
  declare module.exports: $Exports<'react-materialize/lib/Autocomplete/Autocomplete'>;
}
declare module 'react-materialize/lib/Autocomplete/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Autocomplete/index'>;
}
declare module 'react-materialize/lib/Badge.js' {
  declare module.exports: $Exports<'react-materialize/lib/Badge'>;
}
declare module 'react-materialize/lib/Badge/Badge.js' {
  declare module.exports: $Exports<'react-materialize/lib/Badge/Badge'>;
}
declare module 'react-materialize/lib/Badge/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Badge/index'>;
}
declare module 'react-materialize/lib/Breadcrumb.js' {
  declare module.exports: $Exports<'react-materialize/lib/Breadcrumb'>;
}
declare module 'react-materialize/lib/Breadcrumb/Breadcrumb.js' {
  declare module.exports: $Exports<'react-materialize/lib/Breadcrumb/Breadcrumb'>;
}
declare module 'react-materialize/lib/Breadcrumb/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Breadcrumb/index'>;
}
declare module 'react-materialize/lib/Button.js' {
  declare module.exports: $Exports<'react-materialize/lib/Button'>;
}
declare module 'react-materialize/lib/Button/Button.js' {
  declare module.exports: $Exports<'react-materialize/lib/Button/Button'>;
}
declare module 'react-materialize/lib/Button/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Button/index'>;
}
declare module 'react-materialize/lib/Card.js' {
  declare module.exports: $Exports<'react-materialize/lib/Card'>;
}
declare module 'react-materialize/lib/Card/Card.js' {
  declare module.exports: $Exports<'react-materialize/lib/Card/Card'>;
}
declare module 'react-materialize/lib/Card/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Card/index'>;
}
declare module 'react-materialize/lib/CardPanel.js' {
  declare module.exports: $Exports<'react-materialize/lib/CardPanel'>;
}
declare module 'react-materialize/lib/CardPanel/CardPanel.js' {
  declare module.exports: $Exports<'react-materialize/lib/CardPanel/CardPanel'>;
}
declare module 'react-materialize/lib/CardPanel/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/CardPanel/index'>;
}
declare module 'react-materialize/lib/CardTitle.js' {
  declare module.exports: $Exports<'react-materialize/lib/CardTitle'>;
}
declare module 'react-materialize/lib/CardTitle/CardTitle.js' {
  declare module.exports: $Exports<'react-materialize/lib/CardTitle/CardTitle'>;
}
declare module 'react-materialize/lib/CardTitle/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/CardTitle/index'>;
}
declare module 'react-materialize/lib/Carousel.js' {
  declare module.exports: $Exports<'react-materialize/lib/Carousel'>;
}
declare module 'react-materialize/lib/Carousel/Carousel.js' {
  declare module.exports: $Exports<'react-materialize/lib/Carousel/Carousel'>;
}
declare module 'react-materialize/lib/Carousel/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Carousel/index'>;
}
declare module 'react-materialize/lib/Chip.js' {
  declare module.exports: $Exports<'react-materialize/lib/Chip'>;
}
declare module 'react-materialize/lib/Chip/Chip.js' {
  declare module.exports: $Exports<'react-materialize/lib/Chip/Chip'>;
}
declare module 'react-materialize/lib/Chip/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Chip/index'>;
}
declare module 'react-materialize/lib/Col.js' {
  declare module.exports: $Exports<'react-materialize/lib/Col'>;
}
declare module 'react-materialize/lib/Col/Col.js' {
  declare module.exports: $Exports<'react-materialize/lib/Col/Col'>;
}
declare module 'react-materialize/lib/Col/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Col/index'>;
}
declare module 'react-materialize/lib/Collapsible.js' {
  declare module.exports: $Exports<'react-materialize/lib/Collapsible'>;
}
declare module 'react-materialize/lib/Collapsible/Collapsible.js' {
  declare module.exports: $Exports<'react-materialize/lib/Collapsible/Collapsible'>;
}
declare module 'react-materialize/lib/Collapsible/CollapsibleItem.js' {
  declare module.exports: $Exports<'react-materialize/lib/Collapsible/CollapsibleItem'>;
}
declare module 'react-materialize/lib/Collapsible/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Collapsible/index'>;
}
declare module 'react-materialize/lib/CollapsibleItem.js' {
  declare module.exports: $Exports<'react-materialize/lib/CollapsibleItem'>;
}
declare module 'react-materialize/lib/Collection.js' {
  declare module.exports: $Exports<'react-materialize/lib/Collection'>;
}
declare module 'react-materialize/lib/Collection/Collection.js' {
  declare module.exports: $Exports<'react-materialize/lib/Collection/Collection'>;
}
declare module 'react-materialize/lib/Collection/CollectionItem.js' {
  declare module.exports: $Exports<'react-materialize/lib/Collection/CollectionItem'>;
}
declare module 'react-materialize/lib/Collection/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Collection/index'>;
}
declare module 'react-materialize/lib/CollectionItem.js' {
  declare module.exports: $Exports<'react-materialize/lib/CollectionItem'>;
}
declare module 'react-materialize/lib/constants.js' {
  declare module.exports: $Exports<'react-materialize/lib/constants'>;
}
declare module 'react-materialize/lib/Container.js' {
  declare module.exports: $Exports<'react-materialize/lib/Container'>;
}
declare module 'react-materialize/lib/Container/Container.js' {
  declare module.exports: $Exports<'react-materialize/lib/Container/Container'>;
}
declare module 'react-materialize/lib/Container/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Container/index'>;
}
declare module 'react-materialize/lib/Divider.js' {
  declare module.exports: $Exports<'react-materialize/lib/Divider'>;
}
declare module 'react-materialize/lib/Divider/Divider.js' {
  declare module.exports: $Exports<'react-materialize/lib/Divider/Divider'>;
}
declare module 'react-materialize/lib/Divider/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Divider/index'>;
}
declare module 'react-materialize/lib/Dropdown.js' {
  declare module.exports: $Exports<'react-materialize/lib/Dropdown'>;
}
declare module 'react-materialize/lib/Dropdown/Dropdown.js' {
  declare module.exports: $Exports<'react-materialize/lib/Dropdown/Dropdown'>;
}
declare module 'react-materialize/lib/Dropdown/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Dropdown/index'>;
}
declare module 'react-materialize/lib/Footer.js' {
  declare module.exports: $Exports<'react-materialize/lib/Footer'>;
}
declare module 'react-materialize/lib/Footer/Footer.js' {
  declare module.exports: $Exports<'react-materialize/lib/Footer/Footer'>;
}
declare module 'react-materialize/lib/Footer/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Footer/index'>;
}
declare module 'react-materialize/lib/Icon.js' {
  declare module.exports: $Exports<'react-materialize/lib/Icon'>;
}
declare module 'react-materialize/lib/Icon/Icon.js' {
  declare module.exports: $Exports<'react-materialize/lib/Icon/Icon'>;
}
declare module 'react-materialize/lib/Icon/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Icon/index'>;
}
declare module 'react-materialize/lib/idgen.js' {
  declare module.exports: $Exports<'react-materialize/lib/idgen'>;
}
declare module 'react-materialize/lib/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/index'>;
}
declare module 'react-materialize/lib/index.old.js' {
  declare module.exports: $Exports<'react-materialize/lib/index.old'>;
}
declare module 'react-materialize/lib/Input.js' {
  declare module.exports: $Exports<'react-materialize/lib/Input'>;
}
declare module 'react-materialize/lib/Input/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Input/index'>;
}
declare module 'react-materialize/lib/Input/Input.js' {
  declare module.exports: $Exports<'react-materialize/lib/Input/Input'>;
}
declare module 'react-materialize/lib/MediaBox.js' {
  declare module.exports: $Exports<'react-materialize/lib/MediaBox'>;
}
declare module 'react-materialize/lib/MediaBox/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/MediaBox/index'>;
}
declare module 'react-materialize/lib/MediaBox/MediaBox.js' {
  declare module.exports: $Exports<'react-materialize/lib/MediaBox/MediaBox'>;
}
declare module 'react-materialize/lib/MenuItem.js' {
  declare module.exports: $Exports<'react-materialize/lib/MenuItem'>;
}
declare module 'react-materialize/lib/MenuItem/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/MenuItem/index'>;
}
declare module 'react-materialize/lib/MenuItem/MenuItem.js' {
  declare module.exports: $Exports<'react-materialize/lib/MenuItem/MenuItem'>;
}
declare module 'react-materialize/lib/Modal.js' {
  declare module.exports: $Exports<'react-materialize/lib/Modal'>;
}
declare module 'react-materialize/lib/Modal/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Modal/index'>;
}
declare module 'react-materialize/lib/Modal/Modal.js' {
  declare module.exports: $Exports<'react-materialize/lib/Modal/Modal'>;
}
declare module 'react-materialize/lib/Navbar.js' {
  declare module.exports: $Exports<'react-materialize/lib/Navbar'>;
}
declare module 'react-materialize/lib/Navbar/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Navbar/index'>;
}
declare module 'react-materialize/lib/Navbar/Navbar.js' {
  declare module.exports: $Exports<'react-materialize/lib/Navbar/Navbar'>;
}
declare module 'react-materialize/lib/NavItem.js' {
  declare module.exports: $Exports<'react-materialize/lib/NavItem'>;
}
declare module 'react-materialize/lib/NavItem/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/NavItem/index'>;
}
declare module 'react-materialize/lib/NavItem/NavItem.js' {
  declare module.exports: $Exports<'react-materialize/lib/NavItem/NavItem'>;
}
declare module 'react-materialize/lib/Overlay.js' {
  declare module.exports: $Exports<'react-materialize/lib/Overlay'>;
}
declare module 'react-materialize/lib/OverlayTrigger.js' {
  declare module.exports: $Exports<'react-materialize/lib/OverlayTrigger'>;
}
declare module 'react-materialize/lib/OverlayTrigger/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/OverlayTrigger/index'>;
}
declare module 'react-materialize/lib/OverlayTrigger/Overlay.js' {
  declare module.exports: $Exports<'react-materialize/lib/OverlayTrigger/Overlay'>;
}
declare module 'react-materialize/lib/OverlayTrigger/OverlayTrigger.js' {
  declare module.exports: $Exports<'react-materialize/lib/OverlayTrigger/OverlayTrigger'>;
}
declare module 'react-materialize/lib/Pagination.js' {
  declare module.exports: $Exports<'react-materialize/lib/Pagination'>;
}
declare module 'react-materialize/lib/Pagination/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Pagination/index'>;
}
declare module 'react-materialize/lib/Pagination/Pagination.js' {
  declare module.exports: $Exports<'react-materialize/lib/Pagination/Pagination'>;
}
declare module 'react-materialize/lib/Pagination/PaginationButton.js' {
  declare module.exports: $Exports<'react-materialize/lib/Pagination/PaginationButton'>;
}
declare module 'react-materialize/lib/PaginationButton.js' {
  declare module.exports: $Exports<'react-materialize/lib/PaginationButton'>;
}
declare module 'react-materialize/lib/Parallax.js' {
  declare module.exports: $Exports<'react-materialize/lib/Parallax'>;
}
declare module 'react-materialize/lib/Parallax/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Parallax/index'>;
}
declare module 'react-materialize/lib/Parallax/Parallax.js' {
  declare module.exports: $Exports<'react-materialize/lib/Parallax/Parallax'>;
}
declare module 'react-materialize/lib/Preloader.js' {
  declare module.exports: $Exports<'react-materialize/lib/Preloader'>;
}
declare module 'react-materialize/lib/Preloader/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Preloader/index'>;
}
declare module 'react-materialize/lib/Preloader/Preloader.js' {
  declare module.exports: $Exports<'react-materialize/lib/Preloader/Preloader'>;
}
declare module 'react-materialize/lib/ProgressBar.js' {
  declare module.exports: $Exports<'react-materialize/lib/ProgressBar'>;
}
declare module 'react-materialize/lib/ProgressBar/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/ProgressBar/index'>;
}
declare module 'react-materialize/lib/ProgressBar/ProgressBar.js' {
  declare module.exports: $Exports<'react-materialize/lib/ProgressBar/ProgressBar'>;
}
declare module 'react-materialize/lib/Row.js' {
  declare module.exports: $Exports<'react-materialize/lib/Row'>;
}
declare module 'react-materialize/lib/Row/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Row/index'>;
}
declare module 'react-materialize/lib/Row/Row.js' {
  declare module.exports: $Exports<'react-materialize/lib/Row/Row'>;
}
declare module 'react-materialize/lib/SearchForm.js' {
  declare module.exports: $Exports<'react-materialize/lib/SearchForm'>;
}
declare module 'react-materialize/lib/SearchForm/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/SearchForm/index'>;
}
declare module 'react-materialize/lib/SearchForm/SearchForm.js' {
  declare module.exports: $Exports<'react-materialize/lib/SearchForm/SearchForm'>;
}
declare module 'react-materialize/lib/Section.js' {
  declare module.exports: $Exports<'react-materialize/lib/Section'>;
}
declare module 'react-materialize/lib/Section/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Section/index'>;
}
declare module 'react-materialize/lib/Section/Section.js' {
  declare module.exports: $Exports<'react-materialize/lib/Section/Section'>;
}
declare module 'react-materialize/lib/SideNav.js' {
  declare module.exports: $Exports<'react-materialize/lib/SideNav'>;
}
declare module 'react-materialize/lib/SideNav/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/SideNav/index'>;
}
declare module 'react-materialize/lib/SideNav/SideNav.js' {
  declare module.exports: $Exports<'react-materialize/lib/SideNav/SideNav'>;
}
declare module 'react-materialize/lib/SideNav/SideNavItem.js' {
  declare module.exports: $Exports<'react-materialize/lib/SideNav/SideNavItem'>;
}
declare module 'react-materialize/lib/SideNavItem.js' {
  declare module.exports: $Exports<'react-materialize/lib/SideNavItem'>;
}
declare module 'react-materialize/lib/Slide.js' {
  declare module.exports: $Exports<'react-materialize/lib/Slide'>;
}
declare module 'react-materialize/lib/Slide/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Slide/index'>;
}
declare module 'react-materialize/lib/Slide/Slide.js' {
  declare module.exports: $Exports<'react-materialize/lib/Slide/Slide'>;
}
declare module 'react-materialize/lib/Slider.js' {
  declare module.exports: $Exports<'react-materialize/lib/Slider'>;
}
declare module 'react-materialize/lib/Slider/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Slider/index'>;
}
declare module 'react-materialize/lib/Slider/Slider.js' {
  declare module.exports: $Exports<'react-materialize/lib/Slider/Slider'>;
}
declare module 'react-materialize/lib/Spinner.js' {
  declare module.exports: $Exports<'react-materialize/lib/Spinner'>;
}
declare module 'react-materialize/lib/Spinner/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Spinner/index'>;
}
declare module 'react-materialize/lib/Spinner/Spinner.js' {
  declare module.exports: $Exports<'react-materialize/lib/Spinner/Spinner'>;
}
declare module 'react-materialize/lib/Tab.js' {
  declare module.exports: $Exports<'react-materialize/lib/Tab'>;
}
declare module 'react-materialize/lib/Tab/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Tab/index'>;
}
declare module 'react-materialize/lib/Tab/Tab.js' {
  declare module.exports: $Exports<'react-materialize/lib/Tab/Tab'>;
}
declare module 'react-materialize/lib/Table.js' {
  declare module.exports: $Exports<'react-materialize/lib/Table'>;
}
declare module 'react-materialize/lib/Table/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Table/index'>;
}
declare module 'react-materialize/lib/Table/Table.js' {
  declare module.exports: $Exports<'react-materialize/lib/Table/Table'>;
}
declare module 'react-materialize/lib/Tabs.js' {
  declare module.exports: $Exports<'react-materialize/lib/Tabs'>;
}
declare module 'react-materialize/lib/Tabs/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Tabs/index'>;
}
declare module 'react-materialize/lib/Tabs/Tabs.js' {
  declare module.exports: $Exports<'react-materialize/lib/Tabs/Tabs'>;
}
declare module 'react-materialize/lib/Tag.js' {
  declare module.exports: $Exports<'react-materialize/lib/Tag'>;
}
declare module 'react-materialize/lib/Tag/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Tag/index'>;
}
declare module 'react-materialize/lib/Tag/Tag.js' {
  declare module.exports: $Exports<'react-materialize/lib/Tag/Tag'>;
}
declare module 'react-materialize/lib/Toast.js' {
  declare module.exports: $Exports<'react-materialize/lib/Toast'>;
}
declare module 'react-materialize/lib/Toast/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/Toast/index'>;
}
declare module 'react-materialize/lib/Toast/Toast.js' {
  declare module.exports: $Exports<'react-materialize/lib/Toast/Toast'>;
}
declare module 'react-materialize/lib/UserView.js' {
  declare module.exports: $Exports<'react-materialize/lib/UserView'>;
}
declare module 'react-materialize/lib/UserView/index.js' {
  declare module.exports: $Exports<'react-materialize/lib/UserView/index'>;
}
declare module 'react-materialize/lib/UserView/UserView.js' {
  declare module.exports: $Exports<'react-materialize/lib/UserView/UserView'>;
}
declare module 'react-materialize/lib/utils/constants.js' {
  declare module.exports: $Exports<'react-materialize/lib/utils/constants'>;
}
declare module 'react-materialize/lib/utils/idgen.js' {
  declare module.exports: $Exports<'react-materialize/lib/utils/idgen'>;
}
