'use strict';

module.exports = (facility) => {
  return [
    {serviceName: 'Pill', value: facility[241]},
    {serviceName: 'Pill', value: facility[242]},
    {serviceName: 'Injectable', value: facility[243]},
    {serviceName: 'Progesterone only injectable', value: facility[244]},
    {serviceName: 'Male condoms', value: facility[245]},
    {serviceName: 'Female condoms', value: facility[246]},
    {serviceName: 'Intrauterine Device (IUD)', value: facility[247]},
    {serviceName: 'Implant', value: facility[248]},
    {serviceName: 'Cycle Beads', value: facility[249]},
    {serviceName: 'Emergency Contraception', value: facility[250]},
    {serviceName: 'Male Sterilisation', value: facility[251]},
    {serviceName: 'Female Sterilisation', value: facility[252]},
    {serviceName: 'Depoprovera', value: facility[253]},
    {serviceName: 'Vortex mixer', value: facility[606]},
    {serviceName: 'Pipettes', value: facility[607]},
    {serviceName: 'Tomography', value: facility[609]},
    {serviceName: 'X-Ray', value: facility[610]},
    {serviceName: 'USS', value: facility[611]},
    {serviceName: 'Functional ECG', value: facility[612]},
    {serviceName: 'Injectable Contraceptive', value: facility[258]},
    {serviceName: 'Injectable Contraceptive ', value: facility[259]},
    {serviceName: 'Male condoms', value: facility[260]},
    {serviceName: 'Female condoms', value: facility[261]},
    {serviceName: 'Intrauterine Device (IUCD)', value: facility[262]},
    {serviceName: 'Implants', value: facility[263]},
    {serviceName: 'Cycle Beads', value: facility[264]},
    {serviceName: 'Emergency Contraceptives', value: facility[265]},
    {serviceName: 'Male Sterilisation', value: facility[266]},
    {serviceName: 'Male Sterilisation', value: facility[267]},
    {serviceName: 'Depoprovera', value: facility[268]},
    {serviceName: 'Levonorgestrel', value: facility[271]},
    {serviceName: 'Ulipristal Acetate', value: facility[272]},
    {serviceName: 'Misoprostol', value: facility[279]},
    {serviceName: 'ANC guidelines', value: facility[280]},
    {serviceName: 'ANC job aid', value: facility[281]},
    {serviceName: 'IPT guidelines', value: facility[282]},
    {serviceName: 'HIV Testing', value: facility[287]},
    {serviceName: 'ARV Prophylaxis', value: facility[288]},
    {serviceName: 'ART for Pregnant women', value: facility[289]},
    {serviceName: 'ARV prohpylaxis  for newborn', value: facility[290]},
    {serviceName: 'Antibiotics', value: facility[301]},
    {serviceName: 'Parentel oxytocin', value: facility[302]},
    {serviceName: 'Magnesium sulphate', value: facility[303]},
    {serviceName: 'Assisted vaginal', value: facility[304]},
    {serviceName: 'Manual removal of placenta', value: facility[305]},
    {serviceName: 'Removal of concetpion products', value: facility[306]},
    {serviceName: 'Neonatal Rescucitation', value: facility[307]},
    {serviceName: 'Caesarian section', value: facility[308]},
    {serviceName: 'Blood transfusion', value: facility[309]},
    {serviceName: 'Successiful Deliveries', value: facility[310]},
    {serviceName: 'Maternal Deaths', value: facility[311]},
    {serviceName: 'Obstetric Referrals', value: facility[312]},
    {serviceName: 'Ceasarian section', value: facility[313]},
    {serviceName: 'Emergencey Ceasarian Section', value: facility[315]},
    {serviceName: 'Obstetric Guidelines', value: facility[316]},
    {serviceName: 'Sucntion bulb single use', value: facility[321]},
    {serviceName: 'Sunction bulb multiuse', value: facility[322]},
    {serviceName: 'Obstetric care medicines', value: facility[324]},
    {serviceName: 'Eye ointment', value: facility[325]},
    {serviceName: 'Gentamycin injectable 40mg', value: facility[326]},
    {serviceName: 'Gentamycin injectable 20mg', value: facility[327]},
    {serviceName: 'Gentamycin 10mg', value: facility[328]},
    {serviceName: 'Ampicilin', value: facility[329]},
    {serviceName: 'Hydralazine', value: facility[330]},
    {serviceName: 'Metronidazole', value: facility[331]},
    {serviceName: 'Azithromycin', value: facility[332]},
    {serviceName: 'Cefixime', value: facility[333]},
    {serviceName: 'Benzathine/Benzylpenicin', value: facility[334]},
    {serviceName: 'Nifedipe', value: facility[335]},
    {serviceName: 'Methyldopa', value: facility[336]},
    {serviceName: 'Calcium gluconate', value: facility[337]},
    {serviceName: 'Magnesium Sulphate', value: facility[338]},
    {serviceName: 'Skin disinfectant', value: facility[339]},
    {serviceName: 'Chlorhexidine', value: facility[340]},
    {serviceName: 'IV Solutions', value: facility[341]},
    {serviceName: 'Urine protein dip stick test', value: facility[530]},
    {serviceName: 'Urine glucose test', value: facility[531]},
    {serviceName: 'Urine keton test', value: facility[532]},
    {serviceName: 'DBS', value: facility[533]},
    {serviceName: 'Malaria rapid test', value: facility[534]},
    {serviceName: 'MRDT available', value: facility[535]},
    {serviceName: 'Syphillis rpid test', value: facility[536]},
    {serviceName: 'Pregnancy test', value: facility[537]},
    {serviceName: 'Pregnancy test', value: facility[538]},
    {serviceName: 'Urine protein test', value: facility[539]},
    {serviceName: 'Blood glucose test', value: facility[540]},
    {serviceName: 'Ketone test', value: facility[541]},
    {serviceName: 'DBS', value: facility[542]},
    {serviceName: 'RDTS stock out', value: facility[543]},
    {serviceName: 'Days with stock out', value: facility[544]},
    {serviceName: 'Blood sugar test', value: facility[545]},
    {serviceName: 'Full blood count', value: facility[546]},
    {serviceName: 'Microscopy', value: facility[547]},
    {serviceName: 'HIV test', value: facility[548]},
    {serviceName: 'Elisa-HIV antibody test', value: facility[549]},
    {serviceName: 'Glass slides and cover slips', value: facility[550]},
    {serviceName: 'Refridgerator', value: facility[552]},
    {serviceName: 'Glucometer', value: facility[553]},
    {serviceName: 'Glucometer test strips', value: facility[554]},
    {serviceName: 'Wright giemsa stain', value: facility[556]},
    {serviceName: 'Elisa washer', value: facility[557]},
    {serviceName: 'Elisa reader', value: facility[558]},
    {serviceName: 'Incubator', value: facility[559]},
    {serviceName: 'Elisa Assay kit', value: facility[560]},
    {serviceName: 'Acredited microscopist', value: facility[561]},
    {serviceName: 'Xpert mtb testing', value: facility[566]},
    {serviceName: 'Laptop for mtb testing', value: facility[567]},
    {serviceName: 'Cartilage for mtb testing', value: facility[568]},
    {serviceName: 'Liver function test', value: facility[569]},
    {serviceName: 'Alt testing', value: facility[570]},
    {serviceName: 'Serum creatine test', value: facility[572]},
    {serviceName: 'Renal function test', value: facility[573]},
    {serviceName: 'Blood group serology', value: facility[584]},
    {serviceName: 'Blood group testing ', value: facility[585]},
    {serviceName: 'Rhesus blood group testing', value: facility[586]},
    {serviceName: 'Agglutination test', value: facility[587]},
    {serviceName: 'Anti globin testing', value: facility[588]},
    {serviceName: 'Centrifuge and cross match', value: facility[589]},
    {serviceName: 'Grouping  and cross match', value: facility[590]},
    {serviceName: 'Urine microscopy', value: facility[593]},
    {serviceName: 'Syphilis serology testing', value: facility[594]},
    {serviceName: 'Gram stain testing', value: facility[595]},
    {serviceName: 'Csf body fluid count', value: facility[596]},
    {serviceName: 'Csf body fluid count', value: facility[597]},
    {serviceName: 'Serum eletrcolyte', value: facility[599]},
    {serviceName: 'Syphillis serology', value: facility[600]},
    {serviceName: 'Gram stain', value: facility[601]},
    {serviceName: 'White blood counting chamber', value: facility[602]},
    {serviceName: 'Cryptoccocol antigen testing', value: facility[603]},
    {serviceName: 'Power source', value: facility[359]},
    {serviceName: 'PMTCT room', value: facility[298]},
    {serviceName: 'PMTCT guideines', value: facility[294]},
    {serviceName: 'Nutrition Counselling', value: facility[292]},
    {serviceName: 'Iron Supplimentation', value: facility[274]},
    {serviceName: 'Folic acid supplimentation', value: facility[275]},
    {serviceName: 'Betamethasone injectable', value: facility[343]},
    {serviceName: 'Dexamethasone injectable', value: facility[344]},
    {serviceName: 'Oxytocin', value: facility[345]},
    {serviceName: 'Postnatal services', value: facility[349]},
    {serviceName: 'Anaesthetist', value: facility[353]},
    {serviceName: 'Child immunisation', value: facility[354]},
    {serviceName: 'Vaccine storage', value: facility[355]},
    {serviceName: 'Refridgerator', value: facility[356]},
    {serviceName: 'Obstetric Job aid', value: facility[318]},
    {serviceName: 'New born rescucitation', value: facility[319]},
    {serviceName: 'Measles vaccine', value: facility[362]},
    {serviceName: 'Polio vaccine', value: facility[364]},
    {serviceName: 'BCG vaccine', value: facility[365]},
    {serviceName: 'Rotavirus Vaccine', value: facility[366]},
    {serviceName: 'Skilled vaccine  providers', value: facility[368]},
    {serviceName: 'Disposable syringes', value: facility[373]},
    {serviceName: 'Auto-disable syringes', value: facility[374]},
    {serviceName: 'Polio vaccine diluent', value: facility[375]},
    {serviceName: 'BCG vaccine diluent', value: facility[376]},
    {serviceName: 'Pneumococcol vaccine ', value: facility[378]},
    {serviceName: 'DPT Vaccine', value: facility[379]},
    {serviceName: 'Measles vaccine', value: facility[380]},
    {serviceName: 'Measles vaccine stock out', value: facility[381]},
    {serviceName: 'Pentavalet vaccine stock out', value: facility[383]},
    {serviceName: 'Polio vaccine stock out', value: facility[385]},
    {serviceName: 'BCG vaccine stock out', value: facility[386]},
    {serviceName: 'Rota vaccine stock out', value: facility[389]},
    {serviceName: 'ORS provision', value: facility[396]},
    {serviceName: 'Zinc supplimentation', value: facility[397]},
    {serviceName: 'Growth monitoring', value: facility[398]},
    {serviceName: 'Pneumonia Treatment', value: facility[499]},
    {serviceName: 'Amoxixillin Treatment', value: facility[400]},
    {serviceName: 'Malaria Treatment', value: facility[401]},
    {serviceName: 'Iron Suppliment', value: facility[402]},
    {serviceName: 'HTC for minor adolescents', value: facility[406]},
    {serviceName: 'HTC room', value: facility[407]},
    {serviceName: 'RDTS', value: facility[408]},
    {serviceName: 'Condoms', value: facility[409]},
    {serviceName: 'Running water', value: facility[410]},
    {serviceName: 'Hand washing soap', value: facility[411]},
    {serviceName: 'Hand sanitiser', value: facility[412]},
    {serviceName: 'Disposable gloves', value: facility[413]},
    {serviceName: 'Bin', value: facility[414]},
    {serviceName: 'Shaprs Container', value: facility[415]},
    {serviceName: 'Disinfectant', value: facility[416]},
    {serviceName: 'Disposable syringes', value: facility[417]},
    {serviceName: 'Auto disposable Syringes', value: facility[418]},
    {serviceName: 'Staff trained in VCT', value: facility[404]},
    {serviceName: 'ART services', value: facility[419]},
    {serviceName: 'ART providers', value: facility[420]},
    {serviceName: 'ART Pescriptions', value: facility[421]},
    {serviceName: 'ART follow up', value: facility[422]},
    {serviceName: 'National ART guidelines', value: facility[423]},
    {serviceName: 'Palliative care Services', value: facility[427]},
    {serviceName: 'IV Treatment', value: facility[428]},
    {serviceName: 'Cancer Treatment', value: facility[429]},
    {serviceName: 'Nutrition services', value: facility[430]},
    {serviceName: 'Paediatric-HIV servies', value: facility[432]},
    {serviceName: 'TB Treatment', value: facility[433]},
    {serviceName: 'PrepP-Pre exposure prophylaxis', value: facility[434]},
    {serviceName: 'Condoms', value: facility[436]},
    {serviceName: 'HIV and TB screening', value: facility[437]},
    {serviceName: 'HIV-AIDS national guidelines', value: facility[438]},
    {serviceName: 'Palliative care guidelines', value: facility[439]},
    {serviceName: 'STI services', value: facility[441]},
    {serviceName: 'STI diagnosis and management', value: facility[442]},
    {serviceName: 'ST Treatment', value: facility[443]},
    {serviceName: 'National STI guidelines', value: facility[444]},
    {serviceName: 'Smear microscopy', value: facility[449]},
    {serviceName: 'Tuberculosis Culture', value: facility[450]},
    {serviceName: 'Xpert', value: facility[451]},
    {serviceName: 'X-Ray', value: facility[452]},
    {serviceName: 'Facility prescibes TB drugs', value: facility[455]},
    {serviceName: 'Facility provides TB drugs', value: facility[456]},
    {serviceName: 'TB Patient follow up', value: facility[457]},
    {serviceName: 'TB Screening', value: facility[458]},
    {serviceName: 'TB Guideliness', value: facility[459]},
    {serviceName: 'MDR TB guidelines', value: facility[461]},
    {serviceName: 'Staff trained in TB Management', value: facility[463]},
    {serviceName: 'Staff trained in MDR TB', value: facility[465]},
    {serviceName: 'Chronic Respiratory diseases', value: facility[469]},
    {serviceName: 'Peak flow meters', value: facility[473]},
    {serviceName: 'Inhalers', value: facility[474]},
    {serviceName: 'Cervical cancer Diagnosis', value: facility[475]},
    {serviceName: ' Laparatomy provided', value: facility[478]},
    {serviceName: 'Hernia Repair', value: facility[479]},
    {serviceName: 'Neonatal surgery', value: facility[480]},
    {serviceName: 'Cleft Lip repair', value: facility[481]},
    {serviceName: 'Contacture release', value: facility[482]},
    {serviceName: 'Skin grafting', value: facility[483]},
    {serviceName: 'Fracture', value: facility[484]},
    {serviceName: 'Amputation', value: facility[485]},
    {serviceName: 'Cataract Surgery', value: facility[486]},
    {serviceName: 'Rescucitation for adults', value: facility[487]},
    {serviceName: 'Needle holders', value: facility[489]},
    {serviceName: 'Surgical Blades', value: facility[490]},
    {serviceName: 'Retractor', value: facility[491]},
    {serviceName: 'Surgical Scissors', value: facility[492]},
    {serviceName: 'Feeding tubes', value: facility[493]},
    {serviceName: 'Tourniquet', value: facility[494]},
    {serviceName: 'Suction Pump and catheter', value: facility[495]},
    {serviceName: 'Running water', value: facility[500]},
    {serviceName: 'Hand waship soap', value: facility[501]},
    {serviceName: 'Hand sanitiser', value: facility[502]},
    {serviceName: 'Disposable gloves', value: facility[503]},
    {serviceName: 'Bin', value: facility[504]},
    {serviceName: 'Sharp container', value: facility[505]},
    {serviceName: 'Disinfectant', value: facility[506]},
    {serviceName: 'Disposable syringes', value: facility[507]},
    {serviceName: 'Auto disposable syringes', value: facility[508]},
    {serviceName: 'IMEESC trained staff', value: facility[497]},
    {serviceName: 'Staff trained in surgery', value: facility[498]},
    {serviceName: 'Staff trained in anaesthesia', value: facility[499]},
    {serviceName: 'Blood transfusion', value: facility[514]},
    {serviceName: 'Blood stock outs', value: facility[515]},
    {serviceName: 'Blood screening', value: facility[518]},
    {serviceName: 'Blood screened for HIV', value: facility[519]},
    {serviceName: 'Blood screened for Syphillis', value: facility[520]},
    {serviceName: 'Blood screened for Hepatitis C', value: facility[522]},
    {serviceName: 'Refrigerator for storing blood', value: facility[523]},
    {serviceName: 'Diagnostic testing', value: facility[526]},
    {serviceName: 'Rapid Syphillis', value: facility[527]},
    {serviceName: 'Rapid HIV Testing', value: facility[528]},
    {serviceName: 'Centrifuge', value: facility[575]},
    {serviceName: 'FBC-Full blood count', value: facility[578]},
    {serviceName: 'Reagent for FBC', value: facility[580]},
    {serviceName: 'Functional CD4 count', value: facility[581]},
    {serviceName: 'Oral Contraceptives', value: facility[256]},
    {serviceName: 'Management of malnutrition', value: facility[394]},
    {serviceName: 'Staff trained in monitoring', value: facility[370]},
    {
      serviceName: 'Fansidar for malaria prevention (IPT)',
      value: facility[276],
    },
    {
      serviceName: 'Management of High Blood Pressure in Pregnant women',
      value: facility[278],
    },
    {serviceName: 'Staff trained in ANC last 2 years', value: facility[283]},
    {serviceName: 'Staff trained in IPT last 2 years', value: facility[284]},
    {serviceName: 'HIV Counselling for Pregnant women', value: facility[286]},
    {
      serviceName: 'Breastfeeding/feeding options Counselling ',
      value: facility[291],
    },
    {
      serviceName: 'Family planning  counselling to HIV positve pregnant women',
      value: facility[293],
    },
    {
      serviceName: 'Staff trained in PMTCT last 2 years',
      value: facility[295],
    },
    {
      serviceName:
        'Staff trained in infant and young child feeding last 2 years',
      value: facility[296],
    },
    {
      serviceName: 'Infant and young child feeding last 2 years',
      value: facility[297],
    },
    {
      serviceName: 'Active management of third stage of labor',
      value: facility[300],
    },
    {
      serviceName: 'Obstetrics Job aid in maternal and neonatal care ',
      value: facility[317],
    },
    {
      serviceName: 'Neonatal sucntion bulb single use/multiuse ',
      value: facility[320],
    },
    {serviceName: 'Sodium chloride injection solution', value: facility[342]},
    {
      serviceName: 'Guidleines for Management of Obstetric Complications',
      value: facility[350],
    },
    {
      serviceName:
        'Staff trained in  management of complicated Obstetric Cases',
      value: facility[351],
    },
    {serviceName: 'Staff trained in Caesarain section', value: facility[352]},
    {
      serviceName: 'Refridgerator temperature monitoring',
      value: facility[358],
    },
    {serviceName: 'DPT-Hib + Hep B/Pentavalet vaccine', value: facility[363]},
    {
      serviceName: 'Staff trained  in vaccine management',
      value: facility[369],
    },
    {
      serviceName: 'Staff trained in disease surveillance',
      value: facility[371],
    },
    {serviceName: 'Staff trained in injection safety', value: facility[372]},
    {serviceName: 'Penuomoccocal vaccine stock out', value: facility[391]},
    {
      serviceName: 'Vitamin A supplimentation in infants and children',
      value: facility[395],
    },
    {
      serviceName: 'Staff trained in HIV-AIDS prevention',
      value: facility[405],
    },
    {
      serviceName: 'Staff trained in ART in last 2 years',
      value: facility[424],
    },
    {
      serviceName: 'Treatment for Opportunistic infections',
      value: facility[426],
    },
    {serviceName: 'Fortified Protein supplimentation', value: facility[431]},
    {serviceName: 'Family planning for HIV clients', value: facility[435]},
    {
      serviceName: 'Staff trained in HIV-AIDS clinical management',
      value: facility[440],
    },
    {
      serviceName: 'Staff trained in STI diagnosis and management',
      value: facility[445],
    },
    {
      serviceName: 'TB Diagnosis using clinical symptoms',
      value: facility[448],
    },
    {serviceName: 'National guidelines for TB- MDR', value: facility[460]},
    {serviceName: 'TB infection control guidelines', value: facility[462]},
    {
      serviceName: 'Staff trained in HIV-TB coinfection',
      value: facility[464],
    },
    {
      serviceName: 'Staff trained in TB Infection control',
      value: facility[466],
    },
    {serviceName: 'Cardivascular diseases management', value: facility[467]},
    {
      serviceName: 'Chronic Respiratory diseases management',
      value: facility[470],
    },
    {
      serviceName: 'Staff trained in Respiratory Diseases',
      value: facility[471],
    },
    {
      serviceName: 'National guidelines for Cervical cancer',
      value: facility[476],
    },
    {
      serviceName: 'Staff trained in Cervical cancer prevention and control',
      value: facility[477],
    },
    {
      serviceName: 'Rescucitation for peadiatric patients',
      value: facility[588],
    },
    {
      serviceName: 'Cardiovascular disease management guidelines',
      value: facility[468],
    },
    {
      serviceName: 'Staff trained in cardiovascular diseases',
      value: facility[469],
    },
    {
      serviceName: 'National guidelines for Surgical care',
      value: facility[496],
    },
    {serviceName: 'Malaria diagnosis through symptoms', value: facility[511]},
    {
      serviceName: 'Malaria rapid diagnostic test (MRDT)',
      value: facility[512],
    },
    {
      serviceName: 'Blood ordered from national/regional centre',
      value: facility[516],
    },
    {serviceName: 'Blood obtained from other sources', value: facility[517]},
    {serviceName: 'Blood screened for Hepatitis  B', value: facility[521]},
    {serviceName: 'Guidleines for blood transfusion', value: facility[524]},
    {
      serviceName: 'Staff trained in blood transfusion last 2 years',
      value: facility[525],
    },
    {serviceName: 'Urine rapid test  for pregnancy', value: facility[529]},
    {serviceName: 'Calorimeter and haemoglobinometer', value: facility[555]},
    {
      serviceName: 'Zienl Neelsen available and functional',
      value: facility[562],
    },
    {
      serviceName: 'Fluorescence microscope available and functional ',
      value: facility[563],
    },
    {
      serviceName: 'Auramine ohodamine stain for TB microscopy available',
      value: facility[565],
    },
    {
      serviceName: 'Biochemistry analyser for kidney and liver function',
      value: facility[574],
    },
    {
      serviceName: 'Assay kit for kidney and liver functional',
      value: facility[576],
    },
    {serviceName: 'Functional haematology analyzer', value: facility[579]},
    {serviceName: 'Assay kit for CD4 count testing', value: facility[583]},
    {
      serviceName: 'Molecular biological technique for HIV Viral load',
      value: facility[598],
    },
    {
      serviceName: 'Functional assay automated systems for HIV viral load',
      value: facility[604],
    },
    {serviceName: 'Functional diagnostic centrifuge', value: facility[605]},
    {serviceName: 'Functional biochemistry analyzer', value: facility[608]},
    {serviceName: 'Progesterone oral Contraceptive', value: facility[257]},
    {serviceName: 'IMCI Guidelines', value: facility[403]},
    {serviceName: 'Slide microscopy', value: facility[413]},
    {serviceName: 'Malaria diagnosis', value: facility[510]},
  ]; // TODO: FIX
};
